"""create checks documents issues

Revision ID: 341e37aef6e4
Revises: 
Create Date: 2026-09-18 00:28:30.467555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '341e37aef6e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('record_type', sa.Enum('daily', 'weekly', name='recordtype', native_enum=False), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('check_in_progress', 'complete', 'incomplete', name='checkstatus', native_enum=False), nullable=False),
    sa.Column('status_label', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('extracted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_type', 'record_date', 'version', name='uq_check_version')
    )
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('check_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('detected_type', sa.Enum('observation_diary', 'lesson_report', 'parent_feedback', 'specialist_conclusion', name='materialtype', native_enum=False), nullable=True),
    sa.Column('size_kb', sa.Integer(), nullable=False),
    sa.Column('file_format', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('check_id', sa.Uuid(), nullable=False),
    sa.Column('level', sa.Enum('error', 'warning', name='issuelevel', native_enum=False), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issues')
    op.drop_table('documents')
    op.drop_table('checks')
    # ### end Alembic commands ###
